[tox]
envlist =
    py{37,38,310,311}-fastapi68
    py{37,39,310,311}-fastapi{84,100}
    py{310,311,312,313}-fastapi130

[testenv]
deps =
    fastapi130: fastapi>=0.130.0
    fastapi100: fastapi>=0.100.0
    fastapi84: fastapi<=0.84.0
    fastapi68: fastapi<=0.68.1
    py37: pytest==7.4.4
    py38: pytest==8.3.5
    py39: pytest==8.4.2
    py{310,311,312,313}: pytest==9.0.3
    -r{toxinidir}/tests/requirements.txt
allowlist_externals = sh
commands =
    sh build.sh
    pytest
